### ISSUE TITLE
NER tag types

### ISSUE THREAD

**Issue by jfrance1** [hltcoe/golden-horse#10]
Does Goldenhorse output ACE tags, and if not could you please list the tags I should expect to see in my output?

**Comment by VioletPeng** [comment]
Are you inside COE? If yes, I recommend you to look at https://gitlab.hltcoe.jhu.edu/extraction/goldenhorse
For this public repo, I disabled all the concrete related features.

In the gitlab repo, I stored the output tag both in TokenTagging and EntityMentionSet. Look for toolname 'Violet_NER_annotator'.
In this repo, I generated a separate file ${test_data}.prediction to output the prediction. 

In both cases, this only happens when you do --only_test True
