### ISSUE TITLE
data annotation issue

### ISSUE THREAD

**Issue by jellchou** [hltcoe/golden-horse#2]
When I read data in `weiboNER.conll.train`, the word “老人” was annotated as “ 老  B-PER.NOM 人  O”.
Whether could annotate it as “ 老 B-PER.NOM  人 B-PER.NOM”？

**Comment by VioletPeng** [comment]
Hi,

The data was collected from MTurk by merging several annotations from different turkers with majority vote. I did some post-processing to remove the apparently impossible cases, but this one seems to be more tricky. 
We noticed that there are some data quality issue due to the crowd source nature of the data collecting process, and we plan to release an updated version for the dataset by this weekend. Please check back. Thank you for your interest!

**Comment by VioletPeng** [comment]
Hi Jell,
I just pushed an updated version of the data to 
data/weiboNER_2nd_conll.*
We thank Hangfeng He for help cleaning up the data. 
Please see the readme for more information. Thanks!
-Nanyun

**Comment by jellchou** [comment]
Thanks for your careful update.:)
