### ISSUE TITLE
problem using new data 

### ISSUE THREAD

**Issue by harryhaos** [hltcoe/golden-horse#6]
Hi, there. Again, it is  fine to use command in your readme file. But when I use new data "weiboNER_2nd_conll.train", it got some errors, like following: 

> Traceback (most recent call last):
>   File "theano_src/crf_ner.py", line 255, in <module>
>     main(args)
>   File "theano_src/crf_ner.py", line 102, in main
>     train_set, valid_set, test_set, dicts = loaddata(_args.training_data, _args.valid_data, _args.test_data, feature_thresh=_args.ner_feature_thresh, mode=_args.emb_type, test_label=_args.eval_test)
>   File "golden-horse/theano_src/sighan_ner.py", line 145, in loaddata
>     return f()
>   File "golden-horse/theano_src/sighan_ner.py", line 138, in f
>     dict_feature, dict_lex, dict_y = create_dicts(train_name, valid_name, feature_thresh, test_name, mode, anno)
>   File "golden-horse/theano_src/sighan_ner.py", line 79, in create_dicts
>     X = convdata_helper(lwds, llbs, mode, anno)
>   File "golden-horse/theano_src/sighan_ner.py", line 166, in convdata_helper
>     fields = (char, r, labels[count])
> IndexError: list index out of range

I wonder if it is some mistake I made, it's ok to use command like following?

>  python theano_src/crf_ner.py --nepochs 50 --neval_epochs 1 --training_data data/weiboNER_2nd_conll.train --valid_data data/weiboNER_2nd_conll.dev --test_data data/weiboNER_2nd_conll.test --emb_file embeddings/weibo_charpos_vectors --emb_type charpos --save_model_param weibo_best_parameters --eval_test false

I change "nepochs" and "data" above.

**Comment by VioletPeng** [comment]
Oh, it should be working with the command: python theano_src/crf_ner.py --nepochs 50 --neval_epochs 1 --training_data data/weiboNER_2nd_conll.train --valid_data data/weiboNER_2nd_conll.dev --test_data data/weiboNER_2nd_conll.test --emb_file embeddings/weibo_charpos_vectors --emb_type char --save_model_param weibo_best_parameters --eval_test false

The only thing changed was the flag --emb_type
The original code expected the input to be the original characters without the position information. If you want to use character-positional embeddings, the program will call jieba to do the segmentation.
In this case, it's already the character-positional embeddings. By changed the flag --emb_type to char (tell the code to use character embeddings), it will just take the original input without any process. And since we are still loading the pre-trained character-positional embeddings by set --emb_file embeddings/weibo_charpos_vectors, we should be fine. However, This is totally hacky because the command semantics and what the code is really do is mis-matched. Anyway, just for you to quickly try and get some results.

**Comment by harryhaos** [comment]
I see, it ok now
