### ISSUE TITLE
calculate problem 

### ISSUE THREAD

**Issue by harryhaos** [hltcoe/golden-horse#7]
Sorry to bother you again, I was confused that your named entity F1 from [your later paper](http://www.cs.jhu.edu/~npeng/papers/golden_horse_supplement.pdf)
calculate method.
Is "B-PER.NOM" and "B-PER.NAM"  two different class? (It seems to be this in your code but I am not sure.) In other words, if I only want to test named entity F1, can I label it  as "B-PER"? 

And I wonder if maybe you can provide  your **word** emb file. Thanks.

**Comment by VioletPeng** [comment]
Yes, "B-PER.NOM" and "B-PER.NAM" are different; they denote "named entity" and "nominal mention", respectively. If you only want to test named entity, you should ignore the labels of "x-xxx.NOM" (treat them as "O"). We have the both types in our original paper as well.

The word embedding files are too large (3.3G, because there are much more words than characters in Chinese), that was the reason that we did not upload it.

**Comment by harryhaos** [comment]
That is to say, in your "named entity" F1(micro), you count  "B-PER.NAM" but not "B-PER.NOM" ?  "XXX.NOM" treat as "O"?

**Comment by VioletPeng** [comment]
Correct. The results for Named Entity only contain "xxx.NAM", and the results for Nominal Mention only contain "xxx.NOM", overall contains both.
